services:
  db:
    image: mysql:8.0
    container_name: pet_360_db
    restart: always
    environment:
      - MYSQL_DATABASE=u719040383_pet_360
      - MYSQL_ROOT_PASSWORD=AvrBOIR0Pk
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: pet_360_api
    restart: always
    env_file:
    - .env
    ports:
      - "3000:5000"
    environment:
      - DATABASE_URL=mysql://root:AvrBOIR0Pk@db:3306/u719040383_pet_360
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pet_360_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=AvrBOIR0Pk
    depends_on:
      - db

volumes:
  mysql_data: